# HF Space configuration as local file (since no official HF Terraform provider exists,
# we use the local provider for config management and document the space setup)
resource "local_file" "space_config" {
  filename = "${path.module}/generated/.streamlit/config.toml"
  content  = <<-EOT
    [server]
    headless = true
    enableCORS = false
    enableXsrfProtection = false

    [browser]
    gatherUsageStats = false
  EOT
}

resource "local_file" "space_readme" {
  filename = "${path.module}/generated/README.md"
  content  = <<-EOT
    # 🌱 AgriSense AI - ${var.environment}

    **Deployed by Terraform** · Version ${var.app_version} · Environment: ${var.environment}

    Space URL: https://huggingface.co/spaces/${var.hf_username}/${var.space_name}
    Live App: https://${lower(var.hf_username)}-${lower(replace(var.space_name, "-", "-"))}.hf.space

    ---
    Managed via Infrastructure as Code. Do not edit files directly on HF Spaces.
  EOT
}

# GitHub Actions secrets managed via the GitHub provider
resource "github_actions_secret" "hf_token" {
  repository      = var.github_repo
  secret_name     = "AgriSense"
  plaintext_value = var.hf_token
}

resource "github_actions_secret" "hf_username" {
  repository      = var.github_repo
  secret_name     = "HF_USERNAME"
  plaintext_value = var.hf_username
}

# Documentation output showing the full deployment topology
resource "local_file" "deployment_manifest" {
  filename = "${path.module}/generated/deployment.yaml"
  content  = <<-EOT
    # AgriSense AI - Deployment Manifest
    # Generated by Terraform - ${timestamp()}
    # Environment: ${var.environment}

    deployment:
      app_name: AgriSense AI
      version: ${var.app_version}
      environment: ${var.environment}

    huggingface:
      username: ${var.hf_username}
      space: ${var.space_name}
      sdk: ${var.space_sdk}
      hardware: ${var.space_hardware}
      url: https://huggingface.co/spaces/${var.hf_username}/${var.space_name}

    github:
      owner: ${var.github_owner}
      repo: ${var.github_repo}
      actions_url: https://github.com/${var.github_owner}/${var.github_repo}/actions

    ci_cd:
      trigger: push to main branch
      workflow: .github/workflows/deploy.yml
      stages:
        - validate (Python syntax check)
        - deploy (upload to HF Spaces)

    infrastructure:
      managed_by: Terraform
      module_path: infrastructure/modules/agrisense
      secrets_backend: GitHub Actions Encrypted Secrets
  EOT
}
